# Python versions for matrix
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install coveralls"
  - pip install -r requirements.txt
  - "pip install ."

# Command to run tests, e.g. python setup.py test
script:
  - py.test

# Report to coveralls
after_success:
  - coveralls
