# Python versions for matrix
language: python
branches:
  only:
    - master

python:
  - "3.5"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install coveralls"
  - pip install -r requirements.txt
  - pip install -e .

# Command to run tests, e.g. python setup.py test
script:
  - pytest tests/test_utils.py

# Report to coveralls
after_success:
  - coveralls
